### ISSUE TITLE
How to make it work in Windows?

### ISSUE THREAD

**Issue by Jeru2023** [ssbuild/chatglm3_finetuning#11]
bitsandbytes does not support Windows by default.

I guess that's why I ran into below issue:
```
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary D:\conda_envs\ai\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
```
I tried to echo $PATH in my bash console, CUDA path is correctly setup already.

Have you ever tried to train the model in Windows env?

**Comment by ssbuild** [comment]
try wsl + nvidia-docker

**Comment by Jeru2023** [comment]
I found a walk around solution to run the script: pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git
But still got a new issue, any change I can change the param to get around it?
`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\conda_envs\ai\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\conda_envs\ai\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
ChatGLMConfig {
  "_name_or_path": "THUDM/chatglm3-6b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1e-05,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 28,
  "original_rope": true,
  "pad_token_id": 0,
  "padded_vocab_size": 65024,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "return_dict": false,
  "rmsnorm": true,
  "seq_length": 8192,
  "task_specific_params": {
    "learning_rate": 2e-05,
    "learning_rate_for_task": 2e-05
  },
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "vocab_size": 65024
}

TrainingArguments(optimizer='lion', optimizer_args=None, scheduler_type='CAWR', scheduler={'T_mult': 1, 'rewarm_epoch_num': 0.5, 'verbose': False}, adv=None, hierarchical_position=None, learning_rate=2e-05, learning_rate_for_task=2e-05, max_epochs=20, max_steps=-1, optimizer_betas=(0.9, 0.999), adam_epsilon=1e-08, gradient_accumulation_steps=1, max_grad_norm=1.0, weight_decay=0, warmup_steps=0, train_batch_size=2, eval_batch_size=2, test_batch_size=2, seed=42, dataloader_drop_last=True, dataloader_num_workers=0, dataloader_pin_memory=True, torch_compile=False, torch_compile_backend=None, torch_compile_mode=None)
ModelArguments(model_name_or_path='D:\\dev\\models\\chatglm3-6b', model_type='chatglm', config_overrides=None, config_name='D:\\dev\\models\\chatglm3-6b\\config.json', tokenizer_name='D:\\dev\\models\\chatglm3-6b', processer_name=None, imageprocesser_name=None, feature_extractor_name=None, cache_dir=None, do_lower_case=None, use_fast_tokenizer=False, model_revision='main', use_auth_token=False, model_custom={})
Traceback (most recent call last):
  File "D:\dev\chatglm3_finetuning\train.py", line 29, in <module>
    main()
  File "D:\dev\chatglm3_finetuning\train.py", line 21, in main
    main_execute()
  File "D:\dev\chatglm3_finetuning\training\train_pl.py", line 110, in main
    pl_model = MyTransformer(**transformer_args)
  File "D:\conda_envs\ai\lib\site-packages\aigc_zoo\utils\transformer_utils.py", line 8, in hf_fn
    fn(self,*args,**kwargs)
  File "D:\conda_envs\ai\lib\site-packages\aigc_zoo\model_zoo\chatglm3\llm_model.py", line 281, in __init__
    super(MyTransformer, self).__init__(*args, **kwargs)
  File "D:\conda_envs\ai\lib\site-packages\deep_training\nlp\models\transformer_base.py", line 268, in __init__
    self.set_model(self.__BACKBONE_CLASS__[0](*args, **kwargs))
  File "D:\conda_envs\ai\lib\site-packages\aigc_zoo\model_zoo\chatglm3\llm_model.py", line 248, in __init__
    self.set_model(self.from_pretrained(MyChatGLMForConditionalGeneration, *args, **kwargs))
  File "D:\conda_envs\ai\lib\site-packages\deep_training\nlp\models\transformer_base.py", line 180, in from_pretrained
    cls_ = CLS.from_pretrained(
  File "D:\conda_envs\ai\lib\site-packages\transformers\modeling_utils.py", line 2719, in from_pretrained
    raise ValueError(
ValueError: You have a version of `bitsandbytes` that is not compatible with 4bit inference and training make sure you have the latest version of `bitsandbytes` installed
`

**Comment by ssbuild** [comment]
modify train_lora.sh   export load_in_bit=0

**Comment by Jeru2023** [comment]
> modify train_lora.sh export load_in_bit=0

Cool, it works now, thank you.
