### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by Essence9999** [ssbuild/chatglm3_finetuning#31]
bash train_lora_int4.sh -m train

train_pl.yaml配置文件
![image](https://github.com/ssbuild/chatglm3_finetuning/assets/66725845/eb3d2879-33d4-4713-9097-f742f101feba)

修改了模型加载路径，加载个人数据集
运行程序一直报OOM（个人配置 A10 24G）
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 386.00 MiB. GPU 0 has a total capacty of 22.02 GiB of which 165.19 MiB is free. Including non-PyTorch memory, this process has 21.86 GiB memory in use. Of the allocated memory 21.13 GiB is allocated by PyTorch, and 458.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 0:   0%|          | 0/64 [00:09<?, ?it/s]

**Comment by Essence9999** [comment]
修改max_seq_length为24，显存吃满，也报OOM

**Comment by ssbuild** [comment]
我测试的 torch 2.1.0 qlora好像16-18g就可以跑！
pip list看一下环境

**Comment by Essence9999** [comment]
> 我测试的 torch 2.1.0 qlora好像16-18g就可以跑！ pip list看一下环境

不好意思，刚测试了一下，发现需要删除scripts/目录下的best_ckpt和outputs_pl文件夹，然后就可以正常训练。
